### ISSUE TITLE
Add project status

### ISSUE THREAD

**Issue by sils** [coala/projects#106]
We probably want projects like "pending" "in progress" and "done" and show them in that order (?) on the page with some headings in between.

**Comment by jayvdb** [comment]
We should include already completed projects from previous gsoc rounds, for completeness, and as guides of what a project should look like through the various phases.
This gets a bit sticky with projects which went sour. Hopefully there are none, and wont be any, but thatis false hope. There will be one, and it will be messy if there is any information retained. Think EU data retention laws and similar. Better to plan ahead for this, then be caught of guard.
Potentially coala needs a contract to cover their butt for publishing the status of a failed project.

**Comment by jayvdb** [comment]
We now have "In progress", but I cant see any way to sort them. cc @hemangsk

It would also be good to include the developer assigned to the in progress projects.

**Comment by sils** [comment]
opened https://github.com/coala/projects/issues/437 because this issue is actually done except the ordering part and the title is misleading
