### ISSUE TITLE
"Coding starts" milestone isn't clear

### ISSUE THREAD

**Issue by sils** [coala/projects#119]
this is the end of community bonding and we should clarify that

difficulty newcomer would be good if someone picks that up soon

**Comment by arnab1896** [comment]
@sils , i think it would be easier to clarify the fact that community bonding period ends if we also include tentative dates. What say you?

**Comment by sils** [comment]
Just name it community bonding?

On Jan 21, 2017 5:13 PM, "arnab1896" <notifications@github.com> wrote:

@sils <https://github.com/sils> , i think it would be easier to clarify the
fact that community bonding period ends if we also include tentative dates.
What say you?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/coala/projects/issues/119#issuecomment-274270861>, or mute
the thread

**Comment by arnab1896** [comment]
1.
![screenshot from 2017-01-22 12-26-02](https://cloud.githubusercontent.com/assets/25241297/22180725/91ce0ede-e09e-11e6-9f13-ce0b64de6abf.png)


2.
![screenshot from 2017-01-22 12-29-57](https://cloud.githubusercontent.com/assets/25241297/22180729/a303cac2-e09e-11e6-91a7-9668b4750046.png)

@sils ; any comments?
1 OR 2, which one should i go for?
