### ISSUE TITLE
URLs dont change if I navigate projects left/right

### ISSUE THREAD

**Issue by sils** [coala/projects#160]

**Comment by gkrishnan724** [comment]
@sils  While doing this change: coala/projects@7ebfe13. I and @hemangsk  did notice this, however we thought that there was no need for the URL to change. Also, I would like to know your views on removing the animation on navigation?

**Comment by gkrishnan724** [comment]
Sorry about this, I just realised that it might create page refresh problems I'll work on this  :+1:

**Comment by impmihai** [comment]
You can simply add `$location.url('?project=' + mval)` on line 55 in app.js in order to update the address.

**Comment by gkrishnan724** [comment]
@impmihai `$location.url('?project=' + mval)` was not included for a reason. `$location.url()` refreshes the page  again which causes modal animation to appear everytime you navigate left/right(which is disturbing).  Right now, you can observe there is no animation on navigating left/right (which is good) however the page url does not change on navigating to different projects. So, what currently needed is a method to change url but not refresh the page ;)

**Comment by impmihai** [comment]
```
			when('/projects', {
				template: '<projects></projects>',
				reloadOnSearch:false
			}).
```
Maybe this helps? I added the reloadOnSearch:false. I tested it on my localhost and it is working well. But i am not sure if this would break any other functionality.
