### ISSUE TITLE
Perhaps there should be a footer 

### ISSUE THREAD

**Issue by Mariatta** [coala/projects#184]
I'm thinking that this site should have a footer, similar to the main coala.io website.

**Comment by aalind0** [comment]
Somewhat like this ?

![new](https://cloud.githubusercontent.com/assets/13695616/22658677/f1695366-ecc0-11e6-9d15-a10e7a9c6fdf.JPG)

**Comment by Mariatta** [comment]
Now, I'm just not sure what kind of agreement we have with the sponsors.
Perhaps other maintainers can comment of whether the sponsors logo should be kept here or not.

**Comment by sims1253** [comment]
@sils has made those arrangements iirc but afaik there is no "you must do this" thing. Also I'm kind of against sponsors on our projects page.

**Comment by Mariatta** [comment]
Thanks for your input, @sims1253 

@aalind0 Let's do the footer but without any of the sponsors logo.

**Comment by aalind0** [comment]
Okay! No partners as well ?

**Comment by sims1253** [comment]
could be interesting to add the colab projects there but that might get crowded fast

**Comment by Mariatta** [comment]
No sponsors & no partners :)

**Comment by ashwini0529** [comment]
We can have a line width footer. Like github has.
<img width="1280" alt="screen shot 2017-02-07 at 12 20 47 am" src="https://cloud.githubusercontent.com/assets/8419333/22661411/4d2c96ea-eccb-11e6-89b4-3bcb7ea9ae15.png">

**Comment by aalind0** [comment]
@ashwini0529 As in the footer we would have to include the list items links such as newcomer docs, code of conduct, etc plus we have to give the twitter and the gitter link. Specifying all of them in a single line would look much crowdy plus would not look much good also. 
I recommend modifying the existing footer only. Plus that would be consistent with coala's main site as well.

**Comment by Mariatta** [comment]
Let's keep the original design that matches coala.io.
Thanks

**Comment by Mariatta** [comment]
So the BDL wants to keep this page relevant to GSoC only, and not be too cluttered.

I got these clear instructions from him 😉 
- Remove sponsors & partner logo from this page
- Chat on gitter should link to https://gitter.im/coala/coala/gsoc
- Keep the links to Documentation, CoC, Newcomer Guide, Blog
- Keep the twitter link
- Remove Donate link

Thanks!

**Comment by Lucifer24** [comment]
@Mariatta Can I work on this?

**Comment by KVGarg** [comment]
@li-boxuan @Mariatta Would like to work on this ?
