### ISSUE TITLE
Project view modal should have two different vertical scrollbars

### ISSUE THREAD

**Issue by ashwini0529** [coala/projects#194]
<img width="1280" alt="screen shot 2017-02-07 at 12 15 10 am" src="https://cloud.githubusercontent.com/assets/8419333/22661275/cf5250c0-ecca-11e6-9b7c-0cb09921905d.png">

The left section and right section should have different scrollbars.

**Comment by meetmangukiya** [comment]
I think it is just about separating the `div`s, labelling low, if it is not feel free to change @hemangsk

**Comment by yash-nisar** [comment]
@etotientz , Our deadline is within a few hours. Please try to incorporate the changes as soon as possible. Thanks ! :smile:

**Comment by etotientz** [comment]
I am trying.But if it is urgent, you can reassign someone else.

**Comment by sils** [comment]
I disagree, why two scrollbars?

**Comment by sils** [comment]
Just make things complicated for the user

**Comment by etotientz** [comment]
yeah,it was looking a bit untidy..A single scroll is better.

**Comment by sils** [comment]
@ashwini0529 can we close this as wontfix or do you disagree?

**Comment by ashwini0529** [comment]
@sils just one issue that the left part is about the project and it still gets scrolled down even if we want to. Is there any other way of solving this?

**Comment by sils** [comment]
not sure what you mean, complicated scrolling behaviour is... well
complicated. And we should avoid that unless there's a bigger benefit IMO
or use a library for that. Do not start to brew an own solution please.

**Comment by yash-nisar** [comment]
Everything is pretty neat, I don't think we need 2 scrollbars. 😄

**Comment by sils** [comment]
enough discussion. This wastes time. Please open an issue with proper reasoning if anyone things there is an issue to solve here.

**Comment by sils** [comment]
(that sounded meaner than intended :D)
