### ISSUE TITLE
Edit command to run website on local machine for Python3

### ISSUE THREAD

**Issue by etotientz** [coala/projects#219]
The SimpleHTTPServer module has been merged into http.server in Python 3.
So the command changes as <python3 -m http.server>  (only for python3)
Check http://stackoverflow.com/questions/7943751/what-is-the-python-3-equivalent-of-python-m-simplehttpserver for more info.

**Comment by jayvdb** [comment]
This was about https://github.com/coala/projects/blob/ed3518837995ac8c277a2c882ed83b9259bb8210/README.md 

Fixed when switching to jekyll .
