### ISSUE TITLE
Broken link for 'existing bear proposal'

### ISSUE THREAD

**Issue by yash-nisar** [coala/projects#221]
Link : http://projects.coala.io/#/projects?project=integrate_pyflakes-enhanced_ast_into_coala_
difficulty/newcomer

**Comment by srisankethu** [comment]
@yash-nisar Hmmm....Try opening the link in a new tab -> [link](http://projects.coala.io/#/projects?project=integrate_pyflakes-enhanced_ast_into_coala_)

**Comment by yash-nisar** [comment]
I meant in the Project "Integrate pyflakes-enhanced AST into coala", under the "Requirements" section, there is a broken link for `existing bear proposal`. @srisankethu

**Comment by Anirudh5** [comment]
@yash-nisar , I want to take up this issue.

**Comment by yash-nisar** [comment]
Sure, you can assign yourself by using `cobot assign full-issue-url` on our gitter channel. Please don't work on issues without assignment as that can lead to conflicts (ie. multiple people working on a single issue)

**Comment by Anirudh5** [comment]
I used that command but I am not able to assign myself the same.

**Comment by Anirudh5** [comment]
@yash-nisar I have done all the required changes and made up a pull request please look forward to it.

**Comment by yash-nisar** [comment]
You have close the PR. There is no need of closing the PR if you make a mistake. You can change your commit by `git commit --amend` and the `git push -f remote branchname`.

**Comment by vVv-AA** [comment]
Seems to be fixed already.

**Comment by Makman2** [comment]
@yash-nisar says this seems to be still an issue :)

**Comment by jayvdb** [comment]
The link it is not broken; the text is broken. Instead of "existing bear proposal", the link target should be "existing bear issues".

**Comment by jayvdb** [comment]
Not worth fixing now the project is completed.
