### ISSUE TITLE
FAQ: Incomplete line

### ISSUE THREAD

**Issue by satwikkansal** [coala/projects#238]
![image](https://cloud.githubusercontent.com/assets/10217535/23578281/2faaa34a-00f9-11e7-8174-3833970ef2c2.png)

^ The last line needs to be completed with appropriate link.

DIfficluty/newcomer

**Comment by satwikkansal** [comment]
Also
![image](https://cloud.githubusercontent.com/assets/10217535/23578359/d39e697c-00fa-11e7-8c07-fd8e51559a94.png)

**Comment by Techievena** [comment]
I have already created an issue for it @satwikkansal https://github.com/coala/projects/issues/234

**Comment by satwikkansal** [comment]
Oh, my bad :worried: Should've checked first. Closing it then!
