### ISSUE TITLE
Typo in the "thesis" faq

### ISSUE THREAD

**Issue by satwikkansal** [coala/projects#240]
![image](https://cloud.githubusercontent.com/assets/10217535/23578343/879898ae-00fa-11e7-93d8-349c2abd7b8b.png)

difficulty/newcomer

**Comment by jayvdb** [comment]
Unassigned due to inactivity

**Comment by RaiVaibhav** [comment]
IMO it should mark only `difficulty/newcomer`

**Comment by prnvdixit** [comment]
Though https://github.com/coala/projects/issues/411 was duplicate of this one, but someone submitted a PR to that duplicate issue - This should be closed now.
