### ISSUE TITLE
Missing Link in "write a thesis with coala"

### ISSUE THREAD

**Issue by Vamshi99** [coala/projects#249]
Change the code accordingly in "thesis.md", to display link at the end of "write a thesis with coala" in FAQ page.

**Comment by patilpushkarp** [comment]
Can you please explain in detail what needs to be done?

**Comment by Vamshi99** [comment]
See http://projects.coala.io/#/faq, a link is missing at the end of "I want to write a thesis with coala!"
![misssinglink](https://cloud.githubusercontent.com/assets/20969586/23785288/020f7a26-058d-11e7-9f0f-a167f18e5e36.PNG)
