### ISSUE TITLE
Remove High involvement tags from projects

### ISSUE THREAD

**Issue by satwikkansal** [coala/projects#291]
These were probably intended for GSoC application phase.

difficulty/newcomer

**Comment by hemanthsavasere** [comment]
Hello @satwikkansal,
I am a newcomer and I want to work on this issue.Can you please guide me.

**Comment by satwikkansal** [comment]
Hey, the aim is basically to remove high involvement tags from projects at
projects.coala.io
You can assign yourself to the issue using cobot on our gitter channel, in
case you need further help... Please feel free to ask in our gitter channel

**Comment by alexwaibel** [comment]
I'd like to be assigned to this issue. I've posted in chat for corbo to assign it to me
