### ISSUE TITLE
Listed items are not rendered correctly

### ISSUE THREAD

**Issue by meetmangukiya** [coala/projects#306]
see the source for the same and the rendered part here : 
http://projects.coala.io/#/projects?project=cobot_enhancement,_testing_and_porting

maybe the markdown renderer isn't working well?
/cc @hemangsk ?

**Comment by hemangsk** [comment]
Solved via https://github.com/coala/coalaCSS/pull/4

**Comment by hemangsk** [comment]
Sorry I misunderstood the issue, its related to rendering of ordered lists and not unordered lists.  Fix
 on the way 👍

**Comment by hemangsk** [comment]
@meetmangukiya fixed 🚀

**Comment by meetmangukiya** [comment]
Works, thanks!
