### ISSUE TITLE
Use cursor pointer when mouse hover over navbar tabs

### ISSUE THREAD

**Issue by Arsfiqball** [coala/projects#318]
Cursor type must be "pointer" when hover over tabs in the header to tell quickly that it is clickable.
difficulty/low

**Comment by jayvdb** [comment]
Is this difficulty newcomer, or difficulty low?
Always add the difficulty to the initial issue description.

**Comment by gabru-md** [comment]
Hi! I would like to do this one. Can you please confirm that the headers are `PROJECTS`  , `MENTORS` and `FAQ` where you want clickable pointers?
Thanks!

**Comment by gabru-md** [comment]
@jayvdb can this issue be assigned to me ? 
I've created a PR for the same.

**Comment by adtac** [comment]
Unassigned @fragm3 due to inactivity for 4 months.

**Comment by aashutoshrathi** [comment]
@jayvdb you removed the linked PR https://github.com/coala/projects/pull/373 from review queue, Can I work on this issue and fix it, as this is an urgent issue, as projects page will get a lot of traffic as GCI and GSoC come closer?
