### ISSUE TITLE
Font size in searchbar becomes very small in small screen

### ISSUE THREAD

**Issue by Arsfiqball** [coala/projects#319]
Why it does not use ordinary size unit like pt instead of vw?
difficulty/low

**Comment by jayvdb** [comment]
Is this difficulty newcomer, or difficulty low?
Always add the difficulty to the initial issue description.

**Comment by khanchi97** [comment]
I want to work on it.Can you please give me some more details about this.

**Comment by jayvdb** [comment]
@khanchi97 , only if you understand the problem, and you want to work on it, use the bot to assign yourself to continue on your 'newcomer' path http://coala.io/newcomer

**Comment by khanchi97** [comment]
Okk @jayvdb  if i find i can do that then i'll use bot assign to get assigned to this.But for 2-3 days i'm busy in registration in my university.

**Comment by gkrishnan724** [comment]
If anyone is working on this, this is the issue screenshot:

![issue](https://user-images.githubusercontent.com/21004514/28464366-70b78252-6e42-11e7-8008-9c409604f44a.png)
