### ISSUE TITLE
Language selector broken in FAQ on Chrome

### ISSUE THREAD

**Issue by jayvdb** [coala/projects#323]
Go to http://projects.coala.io/#/faq in Chrome

Change language to Bahasa.

It changes back to English.

**Comment by Arsfiqball** [comment]
hmm... we need to add some logic in javascript to control the language selector.
Move in-document javascript into proper javascript file.
Lookup for ``lang`` variable in ``localStorage`` and $location.search().lang to decide which language currently used.

**Comment by hemangsk** [comment]
Will be fixed by https://github.com/coala/projects/pull/328

**Comment by Arsfiqball** [comment]
This was already fixed in https://github.com/coala/projects/pull/328
@jayvdb please close the issue :)
