### ISSUE TITLE
GSoC : Final Submission Page

### ISSUE THREAD

**Issue by hemangsk** [coala/projects#337]
GSoC students have to submit a URL to their work for final evaluation to Google. Keeping in mind [Work Submission Guidelines](https://developers.google.com/open-source/gsoc/help/work-product) we could get projects.coala.io to generate a personalised webpage for every student on a link such as https://projects.coala.io/GSoC2017/ < student - name > / .

It could have
-  metadata about student in the header
-  link to their blog
- 3 links (phase 1, 2 and 3) pointing to each of the GitLab milestones. 
- Link to code reviews done
- Summary of GSoC experience

I'd really like to work on this! if this is something we want.

**Comment by meetmangukiya** [comment]
I like the idea, it can serve as an archive :+1:

**Comment by hemangsk** [comment]
This is done

**Comment by hemangsk** [comment]
via https://github.com/coala/projects/commit/661d3a41b7fe1da6b2bab3c217e515b58b27f12d
