### ISSUE TITLE
reports: Make a report list page

### ISSUE THREAD

**Issue by hemangsk** [coala/projects#359]
Task Description : 

1. A proper webpage must be in place using which we can show the list of work submission urls / profiles of GCI and GSOC students. 

2. An overview of webpage structure

- Links of work submission of GSoC Students, sorted yearwise
- Links of work submission / profile of GCI students, sorted yearwise

Steps : 

1. Create  a new layout (.md file) in _layouts directory, and use Jekyll + Liquid syntax to obtain array of all the pages where layout is ```report```  (such pages are in https://github.com/coala/projects/tree/master/reports) .

2. Then you can iterate over this array as many times and show lists of links pertaining to GSoC and GCI, in separate markup sections.

**Comment by hemangsk** [comment]
List For Reference  :

https://projects.coala.io/GSoC/2017/StatusReport/adhikasp
https://projects.coala.io/GSoC/2017/StatusReport/AlexMaxim
https://projects.coala.io/GSoC/2017/StatusReport/HemangKumar
https://projects.coala.io/GSoC/2017/StatusReport/NaveenKumarSangi
https://projects.coala.io/GSoC/2017/StatusReport/RahulJha

cc @sims1253

**Comment by jayvdb** [comment]
I think this should be only about the GSOC reports.

We'll figure out what to do with GCI later. ;-)

**Comment by abhaychawla** [comment]
@hemangsk @jayvdb Can I work on this issue?

**Comment by abhaychawla** [comment]
@Makman2 @hemangsk I got confused a little bit so just wanted to confirm. In this issue, we need to create a new reports tab where in all the links for the projects are to be displayed right? I have worked on angularjs but not enough on jekyll so can you guide me a little bit on what is expected?

**Comment by jayvdb** [comment]
I dont think a new tab is required.

The generated report pages can be linked from the relevant completed projects, e.g. on http://projects.coala.io/#/projects?project=cobot_enhancement,_testing_and_porting , link to https://projects.coala.io/GSoC/2017/StatusReport/MeetMangukiya

and there should be a page at https://projects.coala.io/GSoC/ , which includes links to the 2017 reports

**Comment by abhaychawla** [comment]
Okay will try to complete this as soon as possible!
