### ISSUE TITLE
Link mentor IDs to github profile

### ISSUE THREAD

**Issue by adtac** [coala/projects#36]

**Comment by sils** [comment]
oh did that already

**Comment by li-boxuan** [comment]
We have links to mentors' profile on http://projects.coala.io page, but we don't have links on project detail page, e.g. http://projects.coala.io/#/projects?project=real-time_team_communication_bridge (See the `mentor` tab on sidebar)

**Comment by ashkush21** [comment]
please assign this issue to me, I would like to work on it.

**Comment by li-boxuan** [comment]
@ashkush21 Ask for an invite on gitter channel first.

**Comment by piyush072** [comment]
@li-boxuan I would like to work on this issue.

**Comment by ashkush21** [comment]
@li-boxuan I got access to newcomers group. Can I be assigned this issue now?
