### ISSUE TITLE
Misplaced drop-down for switching languages?

### ISSUE THREAD

**Issue by co-robo** [coala/projects#363]
The drop down seems to have absolute/fixed to lower left corner, but it overlaps with the project cards, hence isn't clickable
Opened by @meetmangukiya at [gitter/coala/coala/offtopic](https://gitter.im/coala/coala/offtopic?at=59a8429619147ac32316343b)

**Comment by gabru-md** [comment]
the drop-down must be on bottom left of the page.
I would like to work on this issue.

**Comment by meetmangukiya** [comment]
@gabru-md go through http://coala.io/newcomer

**Comment by gabru-md** [comment]
I want to work on it. But it seems that i cannot assign myself to this issue.
I believe that this issue is easy. If you could add a difficulty/low tag to it, the maybe i can have it assigned to me. 
Thanks.

**Comment by hemangsk** [comment]
Weird space issue at projects.coala.io , not like the screenshot in PR, cc @gabru-md 
![screen shot 2017-10-29 at 5 30 02 pm](https://user-images.githubusercontent.com/13018570/32143438-05a270c2-bccf-11e7-9a52-3189d09b7765.png)

**Comment by aashutoshrathi** [comment]
@hemangsk is someone working on it? I'm interested
