### ISSUE TITLE
Project name in modal is not perfectly centered

### ISSUE THREAD

**Issue by blazeu** [coala/projects#375]
See [this](https://projects.coala.io/#/projects?project=improve_coala_website_%26_supporting_tools&lang=en) for clear example

Currently it's missing `padding-left`
![screenshot from 2017-10-27 21-23-18](https://user-images.githubusercontent.com/1438859/32108893-4084753c-bb5d-11e7-9946-4c15e026daf8.png)

Adding `padding-left: .5em` and adjusting `padding-right: .5em` will provide a nicer look
![screenshot from 2017-10-27 21-24-24](https://user-images.githubusercontent.com/1438859/32108896-4460cf66-bb5d-11e7-9825-2fbef0e53e70.png)

**Comment by anshumanv** [comment]
I'd like to do this.

**Comment by jayvdb** [comment]
ping @anshumanv

**Comment by anshumanv** [comment]
Thanks for the ping, on it.

**Comment by anshumanv** [comment]
I'm having running issues setting up locally(gems just won't install and can't seem to debug why), you can pass on this issue to others willing to take this up. Thanks :smile:

**Comment by jayvdb** [comment]
btw, we deploy PRs to https://netlify.com, so you can make the change and check that it works on Netlify, without setting up jekyll and verifying it works locally.
