### ISSUE TITLE
Remove _faq/thesis.md link to projects.js

### ISSUE THREAD

**Issue by co-robo** [coala/projects#395]
projects.js doesnt exist.  There isnt a good target for that link, the entire website is projects.
newcomer
Opened by @jayvdb at [Gitter](https://gitter.im/coala/coala?at=59fa005e51915d962afb5e23)

**Comment by jayvdb** [comment]
Also linked on _faq/own_project_idea.md

**Comment by neelanshsahai** [comment]
@jayvdb so should I remove the link or replace it with https://github.com/coala, as here are the list of projects we have.

**Comment by jayvdb** [comment]
probably best to replace with 'projects repository' with a link to this repo, where the README says how to add a project.

**Comment by jckw** [comment]
@jayvdb can I be assigned this issue? I'll fix the PR with a correctly formatted commit message.
