### ISSUE TITLE
Add FAQ entry to say coala will apply to GSOC 2018

### ISSUE THREAD

**Issue by co-robo** [coala/projects#423]
And add a link in FAQ to https://developers.google.com/open-source/gsoc/timeline
Opened by @jayvdb at [Gitter](https://gitter.im/coala/coala/gsoc?at=5a0b062ecc1d527f6b6c6ca7)

**Comment by amitsin6h** [comment]
am working on this as my first contribution. @jayvdb  Thanks

**Comment by prnvdixit** [comment]
@amitsin6h It is recommended to work on a difficulty/newcomer issue first. You can find them at https://coala.io/newcomer. Also, head to https://coala.io/chat and say "Hello World" if you haven't joined the organization yet. Welcome!!

**Comment by amitsin6h** [comment]
@prnvdixit I have been assigned this in gitter chat

**Comment by prnvdixit** [comment]
That's great.... This issue is also of difficulty/newcomer IMO (probably), maybe you can submit a PR for this right away... Though, it's still recommended to do a newcomer issue first before attempting any higher difficulty issue 😄

**Comment by jayvdb** [comment]
As this is very high importance, if you dont finish it within 24 hours, we'll close your PRs and let someone else do it.

**Comment by amitsin6h** [comment]
@jayvdb am gonna do it.

**Comment by yashovardhanagrawal** [comment]
@amitsin6h are you going to complete it?

**Comment by ihsraham** [comment]
If he's not working on it I would like to 😄 

@jayvdb you might assign this to me in that case

**Comment by jayvdb** [comment]
Reassigned.

**Comment by ihsraham** [comment]
@yashovardhanagrawal @jayvdb I have added a PR

**Comment by yashovardhanagrawal** [comment]
@jayvdb 
I think this PR will not work here then

I would like to work on it

**Comment by jayvdb** [comment]
I merged this manually.

@yashovardhanagrawal , you have issues to work on.
