### ISSUE TITLE
Data doesn't load in Chrome

### ISSUE THREAD

**Issue by ashwini0529** [coala/projects#429]
It works perfectly on Safari etc, but it doesn't load data in Chrome.

![screencapture-projects-coala-io-1511441651349](https://user-images.githubusercontent.com/8419333/33173806-7fbee326-d07b-11e7-9777-c2d7b7c411df.png)

**Chrome Version: Version 61.0.3163.100 (Official Build) (64-bit)**
**OS: Mac Os High Sierra 10.13**

Console log for the same: http://paste.ubuntu.com/26027469/

**Comment by xferra** [comment]
Just FYI, works as expected at
**Chome: Version 62.0.3202.94 (Official Build) (64-bit)
OS: macOS Sierra 10.12.6**

**Comment by prakashdanish** [comment]
working for me too, maybe some bad extension? try updating your browser but anyways, we need someone with the same config as yours to test it to confirm.

**Comment by Vamshi99** [comment]
![coala](https://user-images.githubusercontent.com/20969586/33262300-da2e31c8-d38b-11e7-84d4-39b62ed0fb39.PNG)
It doesn't load data on my chrome browser also.
**Chrome Version: Version 62.0.3202.94 (Official Build) (64-bit)**
**OS: Windows 10 Home**

**Comment by SanketDG** [comment]
Please disable your extensions and try again, also see if there's any strange output in the console

**Comment by Vamshi99** [comment]
Tried disabling all extensions, still same blank page. I get some errors in console https://gist.github.com/Vamshi99/9d3844aa0656d99d924dc8f24f9c91ef

**Comment by ashwini0529** [comment]
Almost same errors here as well. 😕

**Comment by jayvdb** [comment]
I am experiencing it as well.

**Comment by Vamshi99** [comment]
Actually, it doesn't happen always. It worked for me until today, I faced it again today after a long time, but it started working normal now. May be It is down due to traffic or something? Need to find the reason first.

**Comment by ashwini0529** [comment]
It works now. 🎉
