### ISSUE TITLE
URL not visible

### ISSUE THREAD

**Issue by jayvdb** [coala/projects#431]
In the answer to https://projects.coala.io/#/faq question "Will coala apply for Google Summer of Code 2018?" , there is a link to the GSOC timeline.

There is no visual indication that a link exists.

**Comment by k4ni5h** [comment]
can i work on this issue?

**Comment by nkprince007** [comment]
@jayvdb. More precisely no link on the page has any visual indication.

**Comment by abhishekr700** [comment]
I don't think we need any visual indication there. Ultimately the person , if interested in the question hovers mouse over the required question , where the mouse icon auto changes to notify that there is a link there.

**Comment by k4ni5h** [comment]
Actually, it is necessary from a user point of view. We have to make right CSS order as its CSS is already defined. I think it is for GCI students as we have to just change the CSS.
