### ISSUE TITLE
Update CI tasks year

### ISSUE THREAD

**Issue by jayvdb** [coala/projects#433]
Update the CI1, CI2 , & CI3 tasks to refer to 2017 , and links to point to the 2017 instance

- CI1: https://codein.withgoogle.com/dashboard/tasks/4705163153506304/
- CI2: https://codein.withgoogle.com/dashboard/tasks/5179714090041344/
- CI3: https://codein.withgoogle.com/dashboard/tasks/6236781315883008/

**Comment by namantw** [comment]
Hello! I am a newcomer, can I work on this issue?

**Comment by namantw** [comment]
@Makman2 I would like to work on this, please assign me.

**Comment by namantw** [comment]
@jayvdb please merge the pull request https://github.com/coala/projects/pull/435, if there are no issues(it is already reviewed)
