### ISSUE TITLE
FAQ: Wrong year on application template

### ISSUE THREAD

**Issue by jayvdb** [coala/projects#441]
http://projects.coala.io/#/faq says "coala 2017 Application Template"

The dates of the coding period are also wrong.

**Comment by suryaprak4sh** [comment]
Hi! I am a newcomer. I read the newcomer's guide. Can you assign me on this issue?

**Comment by suryaprak4sh** [comment]
Hi! I am a newcomer. Can you assign me on this issue?

**Comment by jayvdb** [comment]
@suryaprak4sh , we have a PR by @saraansh1999 ; if they dont fix it quickly, we can re-assign this to you or someone else who will complete the task.

**Comment by Naveenaidu** [comment]
@jayvdb can i please be assigned to this.

**Comment by jayvdb** [comment]
@Naveenaidu , please hurry up; this is urgent.

**Comment by Naveenaidu** [comment]
@jayvdb Made the Changes. Please have a look.
