### ISSUE TITLE
FAQ: Broken link in application template

### ISSUE THREAD

**Issue by jayvdb** [coala/projects#442]
Link to https://github.com/coala/projects/blob/master/data/projects.js is broken

**Comment by suryaprak4sh** [comment]
Hi! Should it refer to the coala website projects?

**Comment by llshwetall** [comment]
hey!
how do I know what the correct link is?

**Comment by yashovardhanagrawal** [comment]
The correct link is 
https://github.com/coala/projects/blob/master/data/projects.liquid
if you're a newcomer, go through the newcomers' guide and go ahead with this issue!

**Comment by Shivank98** [comment]
Hey i am new to coala
@jayvdb @yashovardhanagrawal There is no file in [](https://github.com/coala/projects/tree/master/data)
named project.js .

**Comment by yashovardhanagrawal** [comment]
read the commit on the file projects.liquid

projects.js is converted to -> projects.liquid

**Comment by Shivank98** [comment]
@yagyanshbhatia  ohh i see

**Comment by mittalshravika** [comment]
@jayvdb @yashovardhanagrawal can I work on this starter issue?

**Comment by yashovardhanagrawal** [comment]
@mittalshravika ask a maintainer on the gitter channel to get assigned to this issue, you can work on it then

**Comment by BaffledBadger** [comment]
Can I please be assigned to this issue?
P.S: The broken link is also mentioned in the "I have an own project idea!" section.

**Comment by Makman2** [comment]
Oh @mittalshravika you already had a `difficulty/newcomer` issue, please pick a `difficulty/low` one ;)
