### ISSUE TITLE
nokogiri has a known critical severity (reported by GitHub)

### ISSUE THREAD

**Issue by Makman2** [coala/projects#446]
GitHub suggest to update to 1.8.1

**Comment by jayvdb** [comment]
As a static site, without any XML files, the surface area of this advisory means this project is not impacted at all.
But still useful to remove reliance on old unsupported versions.

**Comment by LenaAn** [comment]
I would like to work on this.

**Comment by Makman2** [comment]
Please accept the invite, then you can be assigned ;)

**Comment by LenaAn** [comment]
done

**Comment by LenaAn** [comment]
Can you please take a look at pr https://github.com/coala/projects/pull/459 ? I believe that
1) gitmate-bot complains about files I didn't edit
2) I try to upgrade nokogiri to 1.8.2 and html-proofer to 3.8.0 so dependencies in Travis CI should be updated as well
