### ISSUE TITLE
Disable OpenRoberta project

### ISSUE THREAD

**Issue by jayvdb** [coala/projects#447]
OpenRoberta is its own org in GSoC 2018.

The project should be disabled, or at least discouraged, unless @maweki is still keen to mentor this project under coala.

There isnt any mechanism for disabling projects yet, but that should be easy to add.

Disabled projects should be greyed out, and mention they are not available.
Ideally add a link to https://summerofcode.withgoogle.com/organizations/6256279438229504/

**Comment by maweki** [comment]
I think you can just remove this. I won't be working at our local roberta partner project from April, so I won't have time to mentor anyways.

**Comment by rohanrk** [comment]
I'd like to finish this and https://github.com/coala/projects/issues/448 since they require the same process on two different projects.
