### ISSUE TITLE
Add link to troubleshooting page of Jekyll

### ISSUE THREAD

**Issue by arnab1896** [coala/projects#457]
Jekyll installation and usage of its gems like bundler can cause some difficulties for newcomers.

So, we can add the link :-   [https://jekyllrb.com/docs/troubleshooting/](url)

So, we can add it in README.md just after we have explained the steps to install jekyll and run the site locally.

**Comment by Bhola-B2C** [comment]
I would like to work on this issue.

**Comment by Bhola-B2C** [comment]
I need to add this hyperlink in README.md ?? Isn't?

**Comment by Bhola-B2C** [comment]
@coala/coala-maintainers plz assign me this issue.
