### ISSUE TITLE
Add GitCommitBear to the Projects repository

### ISSUE THREAD

**Issue by virresh** [coala/projects#463]
Add a GitCommitBear to the .coafile so that commit messages can be checked by coala locally

**Comment by nj2237** [comment]
Hi coala community! Can someone assign this newcomer issue to me? Corobo is refusing to assign :|

**Comment by nj2237** [comment]
@Makman2 Hi there! Could you assign this to me please?

**Comment by refactormyself** [comment]
@jayvdb can I work on this, please assign it to me

**Comment by Makman2** [comment]
You haven't accepted the invite yet via mail.

**Comment by refactormyself** [comment]
@Makman2 that totally escape me. Now I have accepted the invite
