### ISSUE TITLE
Fix typo

### ISSUE THREAD

**Issue by RaiVaibhav** [coala/projects#465]
Fix [typo in line 52 ](https://github.com/coala/projects/blob/0c2f8a0ff4bf4781ed70162293c0274345eb33e5/_projects/bear_updates.md)

Difficulty/newcomer

**Comment by mittalshravika** [comment]
@RaiVaibhav @Makman2 Could this issue be assigned to me?
I am a newcomer into this.
The fix would be to change "indetified" -> "identified"

**Comment by RaiVaibhav** [comment]
It seems you didn't join coala on `gitter`, please say `hello world` on gitter for further instruction :grinning:

**Comment by mittalshravika** [comment]
I just joined gitter some minutes ago and I have asked if this issue could be assigned to me.
Thanks!!

**Comment by jayvdb** [comment]
Assigned.  Be sure to follow https://coala.io/commit

**Comment by mittalshravika** [comment]
I have added a PR for this issue. Waiting for reviews.
Thanks!!

**Comment by RaiVaibhav** [comment]
@mittalshravika reviewed
