### ISSUE TITLE
Add upstream commits to application template

### ISSUE THREAD

**Issue by jayvdb** [coala/projects#469]
This year we will be giving higher consideration to applicants who have commits in upstream repositories, such as our linters, and libraries that coala depends on, either the software or our systems.

Please add an element to the application template to collect this information.

**Comment by Naveenaidu** [comment]
@jayvdb Can i please be assigned to this issue

**Comment by Naveenaidu** [comment]
Am i supposed to add `upstream commits` inside the Project Info section of Application Template?
