### ISSUE TITLE
Text overflowing out of area

### ISSUE THREAD

**Issue by nemaniarjun** [coala/projects#47]
![image](https://cloud.githubusercontent.com/assets/15715894/22026261/49621060-dcf6-11e6-82f7-06b2e19d85fd.png)
See image. Jayvdb is out of the project tab.

**Comment by nemaniarjun** [comment]
Label Design

**Comment by Vamshi99** [comment]
This is same as https://github.com/coala/projects/issues/131

**Comment by hemangsk** [comment]
Closing as this is solved in https://github.com/coala/projects/pull/136
