### ISSUE TITLE
Application Template typo

### ISSUE THREAD

**Issue by ishanSrt** [coala/projects#474]
and ~~to~~ you have any preference for a particular mentor? --> and **do** you have any preference for a particular mentor?

**Comment by sbeesm** [comment]
Hi! New comer here. Can i fix this?

**Comment by sbeesm** [comment]
Hello! New comer here. I would like to work on this, so please assign this issue to me.

**Comment by ishanSrt** [comment]
@sbeesm put a comment for assignment over here https://gitter.im/coala/coala too and start working!

**Comment by jayvdb** [comment]
Duplicate of https://github.com/coala/projects/issues/268
