### ISSUE TITLE
README.md: Dont suggest sudo

### ISSUE THREAD

**Issue by jayvdb** [coala/projects#477]
The README shouldnt require sudo.  Use give instructions on using rbenv instead, if their native ruby isnt correct.

**Comment by jayvdb** [comment]
@Bhola-B2C , you might like to tackle this one.

**Comment by Bhola-B2C** [comment]
Okay I'll tackle this question

**Comment by jayvdb** [comment]
Nice, thanks.

**Comment by Bhola-B2C** [comment]
Install rbenv
$ rbenv install 2.2.3
$ rbenv global 2.2.3
$ gem install jekyll bundler
$ git clone https://github.com/coala/projects.git
$ cd projects
$ bundle install
$ bundle exec jekyll serve

Is it ok??

**Comment by jayvdb** [comment]
@Bhola-B2C , yup perfect, thanks and sorry for the delayed response

**Comment by sanchit48** [comment]
I would like to work on this issue.
