### ISSUE TITLE
Meta-review project

### ISSUE THREAD

**Issue by jayvdb** [coala/projects#480]
An important aspect of newcomer gamification and the undefined developer->maintainer process is good feedback on their reviews.

Any 'points' should be held in waiting until the PRs have been merged, and a developer or maintainer has given feedback on review comments which were given by the newcomer or developer.

A more complete write up is at https://github.com/coala/coala/issues/3615

**Comment by jayvdb** [comment]
Note that https://github.com/coala/projects/blob/master/_projects/newcomer_metrics.md would focus on the newcomers *process*, with only a little consideration given for meta-reviewing.

This project would be about creating a good system for getting developers & maintainers to do meta-reviews.  Probably this is more of a UI project, maybe with a GitHub app which makes meta-review of merged PRs easy to do.

**Comment by jayvdb** [comment]
Some interesting thoughts by @sks444 relevant to both projects at https://gitter.im/coala/community?at=5a9cd82753c1dbb743a4b790

**Comment by jayvdb** [comment]
A very nice place to implement this is inside https://github.com/coala/gh-board , which already has a browser cache of all the issues and PR.  Meta-reviewing issue creation would be a good coding phase 1 deliverable.

gh-board could be expanded to also load the comments and actions to check if there are any comments/actions which need meta-reviewing, and the developer can do meta-review them by opening the issue/PR.

No back-end storage needed.

**Comment by jayvdb** [comment]
A project needs to be written up for this, if it is to proceed.

**Comment by jayvdb** [comment]
fwiw, @li-boxuan & @bekicot , we need two project pages in this repo, one for each of your projects, as they are quite different, and will have different mentors, etc.

**Comment by li-boxuan** [comment]
@jayvdb Regarding https://github.com/coala/projects/issues/480#issuecomment-375966779

> Meta-reviewing issue creation would be a good coding phase 1 deliverable.

Could you elaborate on that?
