### ISSUE TITLE
Move example project to _projects/example.md

### ISSUE THREAD

**Issue by jayvdb** [coala/projects#484]
Currently the README.md includes an example markdown file.  Lets move that to be a real markdown file, ideally in `_projects` , and have jekyll skip it (maybe using `_config.yml` `exclude:` ?)

Alternatively put it somewhere else, where it might be easier to exclude.

**Comment by jayvdb** [comment]
See also https://github.com/coala/projects/issues/490

**Comment by himanshu1603** [comment]
Please assign me this issue!

**Comment by jayvdb** [comment]
The example project is visible in the website.

**Comment by himanshu1603** [comment]
Can I work on this issue?

**Comment by jayvdb** [comment]
ok, sure.
