### ISSUE TITLE
gitmate plugins

### ISSUE THREAD

**Issue by jayvdb** [coala/projects#488]
coala uses http://gitmate.io to automate our systems.

While it works very well, there are a number of plugins which need extra complexity to better suit coala, and there are new plugin ideas we have all the time, but never get around to building.  As these are coala-centric enhancements, they often fall off the gitmate priority list.  The extensible framework is there; we need to utilise it better.

**Comment by jayvdb** [comment]
We have rebase and ff plugins, but a lot of maintainer time can be saved by integrating both of those into an auto-merger.

GitLab has a 'merge when pipelines pass' feature, which GitHub doesnt have.
It would be possible to build GitHub support into the IGitt layer, and needs to be combined with a mechanism for checking it succeeded or failed.

However that is still only operating on a single MR.  Ideally maintainers can approve a few MRs/PRs, and gitmate looks after the details of getting them rebased & merged if there are no conflicts.

**Comment by jayvdb** [comment]
Pull Requests from master should be automatically rejected, with instructions on how to fix their branch, fix their master, and resubmit a PR.

**Comment by jayvdb** [comment]
https://github.com/coala/coala/issues/5155 - Fixes vs Closes automated checking

**Comment by jayvdb** [comment]
Note that https://github.com/coala/projects/pull/489 is a separate project covering enhancements to GitCommitBear especially.

**Comment by jayvdb** [comment]
Another plugin requested is automatically marking WIP if gitmate's coala plugin finds defects.

**Comment by jayvdb** [comment]
A squash command would be useful, to automagically fix a PR with lots of messy commits, so we can merge it - helpful to newcomers only , instead of them creating a new PR.

Actually it would be interesting to see how `rebase` handles a GitHub rebase from master...

Maybe call it something like 'unbork' , so there is a bit of a negative connotation to it, so it isnt used instead of following normal development best practises.

However, there was a suggestion that we move to a GitHub flow , where incremental improvements are added as extra commits until the PR is ready to land, to easy code review, in which case a `squash` at the end would prepare the PR for landing.

**Comment by jayvdb** [comment]
You'll need to ask the gitmate devs, almost all of which are also coala developers.  Their source is at https://gitlab.com/gitmate/open-source

**Comment by Makman2** [comment]
I would like to see advanced configuration management, what I currently have in mind is to manage a set of configurations that can be applied quickly to multiple projects at once or are automatically synced if a repo uses that configuration.
Changing a single setting inside a repo in an organization and making it reflect in all other repos is a pain for 5+ repos.

**Comment by jayvdb** [comment]
@Makman2 , @nkprince007 , see  https://github.com/coala/projects/issues/487 for configuration of gitmate from YAML inside a repo (and we would do the syncing between repos in another tool; likely moban)

**Comment by jayvdb** [comment]
The project page should have been updated during bonding, but too late for that I guess.  See cEP for final project concepts.
