### ISSUE TITLE
coala Language Server

### ISSUE THREAD

**Issue by jayvdb** [coala/projects#492]
https://github.com/coala/coala-vs-code is effectively a Language Server, but with a reduced scope as it is targeted only at vs-code.

It needs to be completed and polished so it can be added to https://langserver.org/

**Comment by jayvdb** [comment]
One component would be docker-ising it, possibly with several dockers for different language sets which include the relevant linters for that language.

e.g. the Python LS at https://github.com/palantir/python-language-server#feature-providers , which uses various tools, and we would use coala for the linting functionality

**Comment by jayvdb** [comment]
https://github.com/coala/coala-vs-code/issues/4 is a possible part of this project, but a 'daemon mode' for coala-core is probably a separate project in itself. @Makman2 , how flexible is the internals of coala to being driven (files pushed onto the queue to be processed) from an external source?

**Comment by gaocegege** [comment]
I will write a description soon.

**Comment by gaocegege** [comment]
https://github.com/coala/projects/pull/495

PTAL

**Comment by jayvdb** [comment]
Closed with https://github.com/coala/projects/pull/495
