### ISSUE TITLE
FAQ about mentoring

### ISSUE THREAD

**Issue by jayvdb** [coala/projects#503]
It should explain the two main roles, 'primary' and 'secondary' mentors, where the former is responsible for the administrative tasks of the project, and the secondary has little to no responsibility, but provides backup and code review for aspects of the project which are relevant to their expertise.

And people interested in mentoring should contact one of the GSoC admin list in the mentors section of the website, indicating the reason their OSS work is suitable for including as a project to be mentored under the coala banner.

**Comment by ShivamSinghania** [comment]
Do I add these details in the mentor_obligations.md file ?

**Comment by jayvdb** [comment]
Yes, https://github.com/coala/projects/blob/master/_faq/mentor_obligations.md is very outdated, before we had a good concept of primary vs secondary mentors.
