### ISSUE TITLE
Quickstart green mode

### ISSUE THREAD

**Issue by jayvdb** [coala/projects#506]
coala-quickstart generates a `.coafile`.

It loads existing meta files, like `.editorconfig` to find rules which are already defined by the repository authors.

Currently it asks the user a lot of questions, and usually generates a `.coafile` which causes `coala-ci` to generate errors.

It could, given more processing time, find most detailed `.coafile` which generates no errors.

i.e. find which set of bears and rules most closely align with the existing source code.

This mode would run coala many times in order to answer questions itself, altering bear settings each time to find the set of settings which produces the least amount of errors, and where necessary adds `ignore` for the remaining files.

It may also use metadata to make decisions without coala invocations.

And it may make sense to include a little aspects work in this project in order to help decision making.  c.f. https://github.com/coala/projects/issues/504

**Comment by satwikkansal** [comment]
This might be relevant https://github.com/coala/coala-quickstart/issues/129

**Comment by satwikkansal** [comment]
> It could, given more processing time, find most detailed .coafile which generates no errors.

i.e. find which set of bears and rules most closely align with the existing source code.

This mode would run coala many times in order to answer questions itself, altering bear settings each time to find the set of settings which produces the least amount of errors, and where necessary adds ignore for the remaining files.

Not sure if I clearly understand what does "error" here mean, is it the actual python errors due to incorrect `.coafile`? or the errors in the codebase detected by running coala on `coafile` generated by quickstart?

**Comment by jayvdb** [comment]
@satwikkansal, maximum number of errors assumes, usually incorrectly, that coala-quickstart & bears is smarter than the repo maintainers.  In reality coala bears are usually not very good.  Worst case is it would recommend tabs for every spaces project, and inverse.  Logic alone forces us to accept that coala is worse than the repos maintainers individually configuring each linter, because coala is a wrapper and the bears have less options than the linter, and only supports a single version of the linter.  coala is however easier to use & manage than 20 different linters.

The way to increase coala adoption is to initially configure the bears to agree with the repo maintainers existing coding style, as that will result in a quickly mergable PR adding the `.coafile`.  They can then make changes to the .coafile and their coding style when they want to, and when the bears actually support their repositories intricacies.

**Comment by satwikkansal** [comment]
Ah, I get it now. So we assume that the project is rightly developed, try to learn its style, and adapt `.coafile` accordingly? The style learning can be done with the help of 

- Meta information found from project (if any)
- Iteratively trying different versions of `.coafile`, and selecting the one which is the most compatible to the project (i.e produces min error)

**Comment by palash25** [comment]
**This is a very rudimentary version of the project that I could come up with**
What if we store certain minimal template .coafiles along with quickstart and add the capability of generating a default but custom .coafile for each project depending upon its metadata (the simplest I can think of are the file extensions) which is inspired from this https://github.com/coala/coala/issues/568
Once quickstart is installed along with all those templates and ran in the repo it will collect the metadata (for the time being just the file extensions) and then combine all those .coafile templates for different languages into a single .coafile for the project and copy it into the root directory of the project.
(I actually made a project along these lines. It was a cli tool to generate `.gitignore` files for any kind of language which is quite similar to this.)

What do you think @jayvdb ?

**Comment by jayvdb** [comment]
We have applicants for this project, so we need it to be on our website.
