### ISSUE TITLE
Duplicate question in application template

### ISSUE THREAD

**Issue by rohanrk** [coala/projects#508]
There is a duplicate geographical boundary question.

- Which country will you reside in during the project?
- Which city (or other geographical boundary you feel comfortable sharing)?

**Comment by jayvdb** [comment]
Dont work on issues without being assigned.  This helps to ensure undesirable changes are not done.

We require country.

We do not require city.

Perhaps the template could be more clear?

**Comment by rohanrk** [comment]
Oh I was a line off when I copy pasted

- Which city, region or other geographical boundary?
  (if you feel comfortable sharing this):
- Which city (or other geographical boundary you feel comfortable sharing)?

These are the duplicated questions.

**Comment by jayvdb** [comment]
ah, re-reviewing...
