### ISSUE TITLE
Have a JSON and MD file per project

### ISSUE THREAD

**Issue by sils** [coala/projects#51]
It'd be nice to write the main description of a project as a markdown file and to have an own JSON per project. So we'd have e.g. `improve_diffs.json` with all the data and `improve_diffs.md` with the description.

**Comment by adtac** [comment]
Nice idea, but this will need like 10-15 JSON requests for the projects page. Unless it's over HTTP/2, this will make the site slower.

**Comment by hemangsk** [comment]
@jayvdb I've begun work on this, so as a proposed solution, we can have one json file with all ```project jsons```, and separate markdown file for each ```project json``` .this way the network issues wont arise.

![screen shot 2017-01-18 at 6 18 33 pm](https://cloud.githubusercontent.com/assets/13018570/22064760/f78e84d4-ddaa-11e6-9e7c-91ec4cf622db.png)

Is this is feasible and in conformity #64?

**Comment by hemangsk** [comment]
Can we close this one. This is resolved by #59

**Comment by sils** [comment]
yes
