### ISSUE TITLE
Add FunctionComplexityCheck bear

### ISSUE THREAD

**Issue by kriti21** [coala/projects#510]
This project is about adding a new bear that checks whether any function/method in the given file is too large/complex and give suggestion to split it into smaller functions.

**Comment by jayvdb** [comment]
Which existing bears already provide this functionality?

**Comment by kriti21** [comment]
None @jayvdb

**Comment by jayvdb** [comment]
> give suggestion to split it into smaller functions

Would your bear emit a message recommending to split the function, or would it provide an actual diff object as a suggestion of how to split the function?

**Comment by kriti21** [comment]
Well that actually depends like for a function that consists of many for / while loops one after the other, or it consists of more than one nested loops or if we could somehow find out the one-half of a function finds out something (a variable value maybe) and the other half actually uses it. For such cases, the bear could suggest where to split the function. But for a really long and complex code, suggesting the user to 'try and split it' should be sufficient. @jayvdb

**Comment by MacBox7** [comment]
By complexity if you mean cyclomatic complexity then we already have some bears for that(RadonBear, ClangComplexityBear, etc). However, if you meant time complexity, then I don't think you can actually find the time complexity of an arbitrary code automatically refer [here](https://stackoverflow.com/questions/9958299/a-tool-for-calculating-the-big-o-time-complexity-of-java-code). Plus providing suggestion as to how to mitigate it, is yet another impossible task IMO.

**Comment by jayvdb** [comment]
We also have complexity bears for JS I believe, and checkstyle does the same for java iirc.

**Comment by jayvdb** [comment]
Project idea is not developed enough for this year, with only a few days to go 

Detecting complexity is old hat stuff. Already done.

Fixing complexity is harder, and could be a project, but requires a round trip-able syntax tree.

We only have the Clang AST, but fixing complexity of C/C++ languages is too crazy . Use go or rust instead.

We have two AST project ideas this year.

So if those projects are successful, next year there will be more ASTs in coala usable for this purpose.

**Comment by jayvdb** [comment]
This proposal cant be developed until after the other projects are completed, and those students will write up new projects which provide the next step forward for those projects.
