### ISSUE TITLE
Add link to Proposal issues on project page

### ISSUE THREAD

**Issue by jayvdb** [coala/projects#521]
Add link to https://github.com/coala/projects/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22Project+Proposal%22

so potential students can see more ideas not yet finished

**Comment by virresh** [comment]
Should this be added as a new tab in the landing page ?

**Comment by jayvdb** [comment]
Maybe a new tab (but it might be rather empty?), or somewhere moderately visible on the Projects tab.

**Comment by virresh** [comment]
A tab entry, which redirects to the above link is what I had in mind

**Comment by jayvdb** [comment]
eww, no redirect pls.  confusing.

**Comment by virresh** [comment]
Uh
okay
Something like this
https://hopeful-thompson-0e3259.netlify.com/#/projects

**Comment by jayvdb** [comment]
No ... a tab has to have content.  no redirect. no offsite link (hidden on mobile).

**Comment by virresh** [comment]
Ah
I understand now
So the offsite link be added as a baner on the projects page below/above the search box ?

**Comment by jayvdb** [comment]
Ya, something like that.  but not too prominent.  "For more project ideas, see ...."

**Comment by virresh** [comment]
Something like this 
https://hopeful-thompson-0e3259.netlify.com/#/projects ?

**Comment by jayvdb** [comment]
good enough

**Comment by virresh** [comment]
okay
I will add a patch then :)
