### ISSUE TITLE
Mark project ideas as crowded

### ISSUE THREAD

**Issue by jayvdb** [coala/projects#522]
The following projects are now crowded

* Commit content checks
* Debug and profile bears
* ANTLRv4
* Improve installation of coala and coala-bears

**Comment by jayvdb** [comment]
c.f. https://github.com/coala/projects/issues/516

**Comment by virresh** [comment]
I would like to work on this :)

**Comment by manankalra** [comment]
On it.

**Comment by manankalra** [comment]
@virresh okay :laughing:
