### ISSUE TITLE
Add FAQ about status high involvement

### ISSUE THREAD

**Issue by jayvdb** [coala/projects#525]
It doesnt have an exact meaning, but it is a suggestion that people shouldnt submit new applications to this project unless they are freaking awesome.

The rough rule I am using is 2+ good proposals, or 3+ reasonable proposals.

**Comment by ShivamSinghania** [comment]
Ok, can you assign this to me ?

**Comment by jayvdb** [comment]
@ShivamSinghania, pick another one ;)
