### ISSUE TITLE
Use text transformations properly

### ISSUE THREAD

**Issue by sils** [coala/projects#54]
http://www.w3schools.com/cssref/pr_text_text-transform.asp

**Comment by naveentata** [comment]
Can any one elaborate this a little bit more?

**Comment by sils** [comment]
sometimes things in the code are manually upper cased, CSS should do that

**Comment by Vamshi99** [comment]
Hi, I am beginner to coala bug fixing. Can anyone tell me what should I do to fix this bug?

**Comment by sils** [comment]
please take another bug if you're not sure what to do here

Sincerely,

Lasse Schuirmann

lasse@schuirmann.net
http://coala.io/ - http://viperdev.io/ - http://gitmate.com/

**Comment by Vamshi99** [comment]
Can anyone explain what is to be done?
Should  we make changes to names of tabs in index.html[1]?
[1](https://github.com/coala/projects/blob/acedc83e7287b65c4b865b49e73b67884c72b10c/index.html#L41-L43)
