### ISSUE TITLE
Add filters for searching projects

### ISSUE THREAD

**Issue by Vamshi99** [coala/projects#559]
Add filters to filter projects by collaborating projects, initiative, mentors, status, difficulty level, tags, etc . Also, have a separate tab for completed projects(maybe also for WIP projects).
label: difficulty/medium

**Comment by suhailsinghbains** [comment]
I think this has been done, I guess.
You can go ahead and close the issue.

**Comment by Vamshi99** [comment]
@suhailsinghbains This isn't done, search is different from filter
Filters are based on a single criteria, such as the mentors
Search is based on all metadata.

**Comment by suhailsinghbains** [comment]
Ohh, interesting!
Thanks for the clarification.

**Comment by KVGarg** [comment]
@Vamshi99 To implements filters, I was thinking to add a `filter button` inside the search bar at the right corner. When that button will be clicked a pop-up block will be displayed with various sub-filters in it - like mentors, status, level, tags etc. ? Is this OK, or you are having an idea about how this enhancement can be achieved ?

**Comment by Vamshi99** [comment]
@KVGarg Seems good, start working on it.

**Comment by KVGarg** [comment]
> Also, have a separate tab for completed projects(maybe also for WIP projects).

Do we need that? Because If we have added filters that can filter projects based on project work status, then I guess this thing will no more be needed.
