### ISSUE TITLE
Split repology project into two projects

### ISSUE THREAD

**Issue by jayvdb** [coala/projects#564]
We have two different projects both utilising Repology for installation.

And there is only one repology project here: https://github.com/coala/projects/blob/master/_projects/automate_dependacy_repology.md

Also relevant is the [`cib`](https://github.com/coala/projects/blob/master/_projects/improve_installation.md) project, which will also be improving our dependency management, but it will be fixing an end-user tool, and will likely be trying to leverage conda to help get the dependencies installed.

As a result, the `cib` project will inevitable be solving the pip dependencies.

The 'Go on BSD' project is clearly about `Go`, and only Go.  The meat of this project is supporting lots of versions of Go, and different BSD, and possible also other more obscure OS like Alpine Linux.

The current repology project is about getting 'all' linters linked to Repology.
I suspect the timeline is not allowing enough time for the process of creating Repology packages for linters that are not yet in Repology, and it seems large numbers of them are missing.  So this will take quite a bit longer than planned.  We'll need to look at various methods of automating the process.  Maybe we rename it to be the 'repology metadata' project.  It will still need to include implementation of the installation routines, but it probably wont have time to solve installation of every bear.  Perhaps it should focus only on linters managed via ruby bundler, and or npm.  That will avoid most conflicts with the other two projects.

@yzgyyang , the first step is for you to create a new very basic proposal page for your project.

**Comment by yukiisbored** [comment]
>I suspect the timeline is not allowing enough time for the process of creating Repology packages for linters that are not yet in Repology

I'm a bit confused with the following statement since you don't add packages directly to repology. Repology just tracks packages on different repositories/OSes, it doesn't actively add them or make a platform to add packages to them. The closest thing I can so for mere users to "edit" it is by Report.

**Comment by yukiisbored** [comment]
I think the whole repology project have works on the following projects:

1. [coala/dependency_management](https://gitlab.com/coala/package_manager) implements the Repology aware stuff (do webcalls to repology API for checking versions, see if it's available in the user's setup, find the best way to solve the dependency, etc)
2. [coala/coala](https://github.com/coala/coala) / [coala/cib](https://gitlab.com/coala/cib) to utilize dependency_management's repology awareness and somehow do it/instruct the user.
3. [coala/coala-bears](https://github.com/coala/coala-bears) to add the needed Repology IDs.

Of course this is just the basic idea, there'll be more problems needed to be solved such as:

1. Some linters require runtime or package managers to be installed, we should add it to the "dependency solver"
2. Should we prioritize using the available system package manager or should we just use the "runtime" package manager?
3. Should coala do it or should we just generate simple instructions for the user to do it themselves or should we have a flag to make coala do it.

... and many more

I think to split it nicely with the skilled students we have for both projects, I'm proposing this:

1. @nemaniarjun will work on the Repology aspect of the project.
2. @yzgyyang will work on the aspects of solving the dependency problem and automating it nicely.

Both sides are quite large and it can't be handled with only one person.

Also, my suggestions above are just suggestions based on my insights and gut-feeling. @nemaniarjun and @yzgyyang still have to find a common middle-ground where they feel both comfortably at.

**Comment by yukiisbored** [comment]
Okay, I think the best to start this of is to simply share your final PDFs with each other and just read it. I'm not sure if it's okay for me to do it myself since it contains your personal information but I can just say both of them have the same goal but they have different routes/timeline to do it. I think it's a good idea to have you both know what similar ideas you have and discuss what's good/bad and make a compromise.

@jayvdb what do you think?

**Comment by anctartica** [comment]
I think the 2 repology projects would be dependent on my project which involves fixing the cib tool so, I would also have to plan my timeline accordingly.

**Comment by nemaniarjun** [comment]
I dont mind sharing my proposal with @yzgyyang

**Comment by xferra** [comment]
As far as I see proposals have the same goal but a little bit different ways to achieve it: "improve" and "change". I suggest that everyone will review both proposals and then chat somewhere in more interactive mode (gitter room?) or even to have a short call to discuss your vision and plans. What do you think?

**Comment by yukiisbored** [comment]
Anyway, deleted my comments since it caused confusion and I didn't read the internal docs about this. Sorry guys^^

**Comment by xferra** [comment]
Ping @neelanshsahai @yzgyyang

**Comment by nemaniarjun** [comment]
@yzgyyang Lets share our proposals with each other after removing any sensitive info. 
This would allow us to get a better idea of our projects and help us in dividing it.

Also as @jayvdb said in the issue description, the first step is for you to create a new very basic proposal page for your project.

**Comment by jayvdb** [comment]
No longer necessary
