### ISSUE TITLE
Remove trailing underscore in pyflakes URL

### ISSUE THREAD

**Issue by jayvdb** [coala/projects#573]
The pyflakes project link is
http://projects.coala.io/#/projects?project=integrate_pyflakes-enhanced_ast_into_coala_

Without the underscore it doesnt work.

http://projects.coala.io/#/projects?project=integrate_pyflakes-enhanced_ast_into_coala

We need both to work, and the former redirect to the latter.

It might be possible to use Netlify `_redirects` to do the redirect.

**Comment by devshiva619** [comment]
@jayvdb hey I would like to work on this

**Comment by jayvdb** [comment]
Assigned.

**Comment by jayvdb** [comment]
Wow, you have also been assigned to https://github.com/coala/projects/issues/529 for ages, and not done anything.
You'll be unassigned soon if you dont submit a PR.

**Comment by devshiva619** [comment]
u can unassign me from #529  👍

**Comment by srivama** [comment]
How about we directly add the redirects in the netlify.toml file instead of creating a new _redirects file?

**Comment by jayvdb** [comment]
As this is a Single Page App, the netlify redirect probably wont work.

Might need some voodoo in the angular JS
