### ISSUE TITLE
.coafile: Set max line length for project pages

### ISSUE THREAD

**Issue by jayvdb** [coala/projects#583]
Similar to https://github.com/coala/cEPs/issues/134 , the project pages (i.e. pages in https://github.com/coala/projects/tree/master/_projects) should have a reasonable line length to improve the ability to read & code review them.

c.f. https://github.com/coala/cEPs/pull/157

Try length 120 for existing files so it requires less disruptive changes to the existing files.

Then add another section which requires 80 cpl and excludes the existing files.

**Comment by JameerBabu** [comment]
Hello everyone, I would like to work on this issue. Please assign me to work on it. @jayvdb please give me a chance.

**Comment by Man-Jain** [comment]
@jayvdb Can you please guide me on how can I do this.
More specifically asking how can I exclude the existing files from the 80 cpl length.

**Comment by jayvdb** [comment]
Please read the issue carefully, as it explains how to proceed, and look at the linked pages and understand them.

**Comment by jayvdb** [comment]
You can list directories in the ignore. Dunno if that helps much.

**Comment by ksdme** [comment]
It looks like 120 CPL isn't enough for old files, you should use the max length that passes all the current files and then ignore them in a new section with 80 CPL limit.

**Comment by Man-Jain** [comment]
@ksdme Yes 120 was not enough so I changed all those lines that were over 120 characters by splitting them up. And I have created the new section which ignores the old files and sets 80 cpl limit to new files.

**Comment by ksdme** [comment]
120 CPL limit for old files is flexible, changing so many files isn't. Change the limit to whatever is required to pass all the files without splitting all the files.

**Comment by Man-Jain** [comment]
I don't think there is a cpl limit that can be applied for all the files as many files were in the range of 200 and 300 and even more than that in some.

**Comment by ksdme** [comment]
Maybe have 300+ CPL, I think it is better than changing all files.

WDYT @jayvdb

**Comment by Man-Jain** [comment]
Okay If the two of you agree. I will do it. :smile:

**Comment by ishanSrt** [comment]
>Maybe have 300+ CPL, I think it is better than changing all files.

@ksdme that surely isn't better that changing files
