### ISSUE TITLE
Typo on title `automate_dependacy_repology.md`

### ISSUE THREAD

**Issue by li-boxuan** [coala/projects#586]
automate_dependacy_repology.md -> automate_dependency_repology.md

https://github.com/coala/projects/blob/e26976aa8da0379c39a4d294ee6cb6e213db1668/_projects/automate_dependacy_repology.md

**Comment by amit2020cs** [comment]
'I want to work on this issue. Can I be assigned please.'

**Comment by nemaniarjun** [comment]
Apologies, as I was the one who created the file in the first place :stuck_out_tongue:
