### ISSUE TITLE
Move site to Netlify

### ISSUE THREAD

**Issue by yukiisbored** [coala/projects#604]
Currently, projects.coala.io results in a TLS certificate failure because GitHub pages doesn't give free certificates for sites outside of *. github.io.

In order to fix this, I suggest moving the site to Netlify where they issue Free Let's Encrypt TLS certificates.

Cc @sils

**Comment by sils** [comment]
@yukiisbored you sure? GitHub should give certs for custom domains for now, I just did that for a page.

**Comment by sils** [comment]
this is what GitHub shows for https for this repo:

```
Enforce HTTPS — Not yet available for your site because the certificate has not finished being issued.
Please allow 24 hours for this process to complete. (projects.coala.io)

HTTPS provides a layer of encryption that prevents others from snooping on or tampering with traffic to your site.
When HTTPS is enforced, your site will only be served over HTTPS. Learn more. 
```

**Comment by virresh** [comment]
Functional again https://projects.coala.io/#/projects
