### ISSUE TITLE
reports: Add tarball hash

### ISSUE THREAD

**Issue by jayvdb** [coala/projects#627]
The reports should include a tarball hash , as a variable in the yaml and this should be displayed beside the tarball in the HTML.

Mentors should check that the hash is correct before approving work reports.

**Comment by jayvdb** [comment]
It can be omitted for the 2017 reports ; we'll create another issue to record those

**Comment by jayvdb** [comment]
As the hashes are already done for 2018 data, please compute the hashes for the 2017 files.

the field name we used was sha256sum iirc

**Comment by KVGarg** [comment]
Ok, I understood what actually is to be done.  I have to compute the hashes for 2017 files and display that computed hash on the webpage below the **download** link of the `patch` for all the reports (2018 and 2017)

**Comment by jayvdb** [comment]
yup; so the downloader can verify they have the correct file, and the tarball (which isnt hosted on coala servers) hasnt been modified since the report was approved and merged.

**Comment by KVGarg** [comment]
I managed to calculate the hash values for 2017 report files and display those hash values on webpage for all reports, but while displaying the hash value in the `Patch Tarball card-view`, it was increasing the size of other `cards` that were opposite to that card. I have attached the screenshot, please check that.
![original](https://user-images.githubusercontent.com/35761292/48124047-67917c80-e2a1-11e8-9489-a41ff7959d6c.png)
To avoid this thing, I have designed 3 designs - please have a look at them and tell me which design will look good on page. or you want me to make any other custom design ?

1.  Design-1

![design-1](https://user-images.githubusercontent.com/35761292/48124410-3bc2c680-e2a2-11e8-8e36-55018018d4fc.png)
2. Design-2
![design-2](https://user-images.githubusercontent.com/35761292/48124411-3c5b5d00-e2a2-11e8-9904-2169b5bb1cc7.png)
3. Design-3
![design-3](https://user-images.githubusercontent.com/35761292/48124414-3c5b5d00-e2a2-11e8-83b3-02822fdc42b6.png)

**Comment by li-boxuan** [comment]
@KVGarg Commit them together.

**Comment by KVGarg** [comment]
For now I'm committing with changes in default design :-)
