### ISSUE TITLE
Update status of 2018 GSoC projects

### ISSUE THREAD

**Issue by jayvdb** [coala/projects#636]
The following are done:

1. https://projects.coala.io/#/projects?project=integrate_antlr_v4_into_coala
1. https://projects.coala.io/#/projects?project=automate_whitelist_creation_for_vulture
1. https://projects.coala.io/#/projects?project=coala_language_server
1. https://projects.coala.io/#/projects?project=commit_content_inspection
1. https://projects.coala.io/#/projects?project=convert_bears_to_aspects
1. https://projects.coala.io/#/projects?project=corobo_enhancements(security,_configurability_and_tests)
1. https://projects.coala.io/#/projects?project=debug_and_profile_bears
1. https://projects.coala.io/#/projects?project=implement_gitmate_plugins_for_coala
1. https://projects.coala.io/#/projects?project=improve_installation_of_coala_and_coala-bears
1. https://projects.coala.io/#/projects?project=integrate_pyflakes-enhanced_ast_into_coala_
1. https://projects.coala.io/#/projects?project=meta-review
1. https://projects.coala.io/#/projects?project=newcomer_metrics_and_gamification
1. https://projects.coala.io/#/projects?project=optimize_caching
1. https://projects.coala.io/#/projects?project=quickstart_green_mode

The following were not started, and should be available again:

- https://projects.coala.io/#/projects?project=handle_nested_programming_languages

The following are incomplete / still in progress, and will need to be closed or heavily revised, and should be marked disabled:

- https://projects.coala.io/#/projects?project=improve_lint_bear_quality
- https://projects.coala.io/#/projects?project=automation_of_dependency_management_using_repology
- https://projects.coala.io/#/projects?project=git_task_list
- https://projects.coala.io/#/projects?project=linter_dependency_management_from_a_bare-metal_system

Non GSoC projects with status unknown:

- https://projects.coala.io/#/projects?project=cohesive_editor_support
- https://projects.coala.io/#/projects?project=implement_jira_support_for_gitmate

**Comment by 123vivekr** [comment]
Can you please assign this issue to me?
