### ISSUE TITLE
Allow Gitbook to edit markdown

### ISSUE THREAD

**Issue by jayvdb** [coala/projects#64]
As part of https://github.com/coala/projects/issues/51 , it would be good to trial editing using gitbook.

I have created 
https://www.gitbook.com/book/coala/projects/
But dont have rights to add the hook to sync the content.

**Comment by jayvdb** [comment]
Commiting from gitbooks is going to require we change the protection on the master branch.
I recommend only rultor and gitbook can commit, and rultor requires gitmate is happy.
But first I need to investigate if gitbook can depend on CI approval.

**Comment by sils** [comment]
@jayvdb is trying around on this one

**Comment by jayvdb** [comment]
Note using forked gitbooks approach is sort of similar to https://github.com/GitbookIO/gitbook/issues/1583#issuecomment-274433447

**Comment by jayvdb** [comment]
The other outstanding problem is https://github.com/GitbookIO/gitbook/issues/1907 .  If that doesnt get resolved soon, we'll need to pin down exactly when these CI triggering events are occurring , and add a rule to our .travis.yml to prevent the builds from starting.
