### ISSUE TITLE
Update the GSoC information link in FAQ's

### ISSUE THREAD

**Issue by shikharvaish28** [coala/projects#642]
The link for 'further information of GSoC' in the FAQ's section is now not supported and has been moved on to a new address. This link needs to be updated.

Link to the page referred: http://projects.coala.io/#/faq

**Comment by nik1082** [comment]
This seems fairly simple, I'll try my hand on this one!

**Comment by vapyc** [comment]
Can you assign this issue to me? But I am completely new so please guide me too.

**Comment by jayvdb** [comment]
@nik1082 is working on this one.

@vapyc , browse through https://coala.io/new for one which you understand how to fix, so you dont need to ask for help on the code -- we will help you when you submit the PR and the bot doesnt like your PR (it is very stringent).

**Comment by kumar1202** [comment]
Please assign this issue to me if no one is working on it.

**Comment by shikharvaish28** [comment]
@kumar1202 

I think @nik1082 is working on this.

**Comment by Ishaan28malik** [comment]
can u please assign #664

**Comment by DaKeiser** [comment]
Can I try this one ?

**Comment by gautamjajoo** [comment]
Hey @li-boxuan Can I work on this issue? The PR seems to be open for a long time.

**Comment by jievince** [comment]
Can you assign it to me? @li-boxuan

**Comment by nishant-sachdeva** [comment]
The link has either been restored or updated through some PR. The 'further information on gsoc'  page is loading fine. @shikharvaish28  it is recommended that this issue be closed now to avoid repetitive PRs.

**Comment by keyurkumbhare** [comment]
@shikharvaish28 @li-boxuan Can you unassign this to whomsoever assigned due to inactivity and assign it to me?

**Comment by vishaldhull09** [comment]
pls assign it to me

**Comment by Shiva-sankaran** [comment]
hey there i am a new comer and would like to work on this issue.I would also like to know why the 2 PR's were disbanded i saw their commits the link was updated was it because they were inactive or is the problem something other than updating the link in .md file

**Comment by Shiva-sankaran** [comment]
I am currently working on this issue and got reviewed  and waiting for getting it merged even though there are no one assigned formally
