### ISSUE TITLE
Create git-bug project

### ISSUE THREAD

**Issue by jayvdb** [coala/projects#648]
https://github.com/MichaelMure/git-bug cc @MichaelMure who has agreed to mentor.

Initial concept is bidirectional sync to GitHub issues with support for bridge impersonating multiple users, e.g. so corobo could be used to create issues as the person who used the bot (or maybe gitmate)

Another idea is GitLab issues support.

Another is a meta-git-bug for handling lots of projects, e.g. super repo with subtrees/submodules/etc of git-bug repos , or housing many GitHub sync'd repos of issue in a single git-bug repo 

Ultimately this needs to be quite a broad project definition at this stage as many medium sized enhancements planned now might be completed before GSoC begins in 2019

Also worth investigating is git-appraise .

**Comment by Anmolbansal1** [comment]
Can I contribute on this project @jayvdb

**Comment by MichaelMure** [comment]
An update here: as of now, the Github importer is working. It's not a yet a full bridge impersonating multiple users, but it's a good step in this direction.

**Comment by sladyn98** [comment]
@MichaelMure seems like an interesting project to work,we could have a discussion on potential solutions and ideas for implementation,would love to consider this as my second proposal for GSOC 19.

**Comment by MichaelMure** [comment]
I wrote an update and more details about this in https://github.com/MichaelMure/git-bug/issues/96
