### ISSUE TITLE
add-repo-license.md: Update a dead link

### ISSUE THREAD

**Issue by haeungun** [coala/projects#660]
When the PR https://github.com/coala/projects/pull/659 is merged 
we noticed that the link(http://besutkode.org/elimination/2016/11/01/31-october-elimination-results/) is broken which is located in `add-repo-license.md` 
we should update this link.

cc: @jayvdb @corona10

**Comment by jayvdb** [comment]
@refeed , @yukiisbored , either of you know what happened here?

**Comment by refeed** [comment]
@jayvdb Sorry, I barely have any idea about what's going on there.

```
$ curl -L "https://besutkode.org" -v
* Rebuilt URL to: https://besutkode.org/
*   Trying 202.3.219.211...
* TCP_NODELAY set
* Connected to besutkode.org (202.3.219.211) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
  CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to besutkode.org:443 
* stopped the pause stream!
* Closing connection 0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to besutkode.org:443
```
Perhaps there's a SSL issue with besutkode.org (?)

**Comment by ananyaarun** [comment]
@haeungun can i work on this issue ?
