### ISSUE TITLE
FAQ question "Will coala apply for Google Summer of Code" should not include year

### ISSUE THREAD

**Issue by srivama** [coala/projects#672]
Currently the FAQ question is in a file called "coala-will-apply-for-gsoc-2018.md"

As coala has been doing GSoC for a few years, we will very likely apply every year. (*)

Having a year in the filename is not good, as the history of this file is "lost" each time it is renamed.

Rename it to "coala-will-apply-for-gsoc.md" , and use "next year" instead of a specific year.

( * Potential students will keep asking the question, even if it is in the FAQ.  If coala stops doing GSoC, the faq will need to be updated )

**Comment by jayvdb** [comment]
I've sent you an invite to join coala.  Please also read https://coala.io/newcomer
