### ISSUE TITLE
Use a better title

### ISSUE THREAD

**Issue by adtac** [coala/projects#68]
Just "coala"? :P

**Comment by sils** [comment]
done

**Comment by sils** [comment]
(I think)

**Comment by adtac** [comment]
Don't think so - the title is still "coala" for me

**Comment by hemangsk** [comment]
Any ideas for title,
```
coala: Interesting projects for everyone
```

**Comment by sils** [comment]
just `coala Projects`?

Sincerely,

Lasse Schuirmann

lasse@schuirmann.net
http://coala.io/ - http://viperdev.io/ - http://gitmate.com/

**Comment by hemangsk** [comment]
sounds better 🎉
