### ISSUE TITLE
Add link to previous GSoC student reports

### ISSUE THREAD

**Issue by li-boxuan** [coala/projects#683]
The link is here: http://projects.coala.io/reports
but it cannot be found on https://projects.coala.io

Can be `difficulty/newcomer` if simply put a link on the page, maybe put the link beside `For more project ideas`, or `difficulty/low` if a bit UI is involved.

**Comment by KVGarg** [comment]
I would like to work upon this issue, can I ?

**Comment by KVGarg** [comment]
I have simply put a link for past years project reports below the project ideas link, Should I create a PR with that change? or Should I work further on improving the UI of reports page ?

**Comment by KVGarg** [comment]
I would have submit a PR, but when i tried to run command `coala--bears PEP8Bear,PyUnusedCodeBear` over my changes it raised some warning over the files which i haven't even changed.
What to do now Should I submit the PR ?
