### ISSUE TITLE
Add details about cEPs to faq

### ISSUE THREAD

**Issue by sks444** [coala/projects#684]
we need a faq entry about what a cEP is and why it is so important to do analysis pre-gsoc, and design as early as possible, to be finalized in the cEP.

Issue ref: https://gitter.im/coala/coala/gsoc?at=5bda923bcd2a6b5bdc78cd2d

Have a look at https://github.com/coala/cEPs

**Comment by KVGarg** [comment]
@sks444 I would like to take up this issue. Can you assign this to me ?
