### ISSUE TITLE
Make the whole mentor card clickable

### ISSUE THREAD

**Issue by adtac** [coala/projects#69]
Not just the user IDs. Oh, and let's have a pointer cursor :)

**Comment by hemangsk** [comment]
Hey @yash10p 😃 , just wanted to confirm whether you're still working on this?

**Comment by yash10p** [comment]
@hemangsk: tried a lot. but couldn't find a suitable fix.

**Comment by sils** [comment]
clearing assignee since nothing has happened for almost a year

**Comment by abhaychawla** [comment]
@sils Can I work on this issue?
