### ISSUE TITLE
coala - A Smartphone Application

### ISSUE THREAD

**Issue by KVGarg** [coala/projects#701]
# Project Proposal Idea
In today's digital world, every individual or a contributor uses a smartphone. And, it becomes difficult to carry laptops everywhere or using a website to browse through issues or commenting on a PR via mobile. For not to happen this, we can create a one-stop application for developers or contributors that can help them to know about our org and provide some features/functionalities to them so that they can contribute to our org, from anywhere at anytime.
Sometimes, a contributors gets into a situation where they think that "I can do much better things then what I am currently doing" or "I can utilize this free time what I have got", this way if they were contributing to our org or want to so some contribution, then that contributor can use this app to know about the org and can do much more things that I will be explaining further what all can a contributor do with this app.
We can provide following features/functionalities to contributors:
1. Newcomer's Section
   - Netlify-form link (existing issue in [community](https://www.github.com/coala/projects/) repository ) or we can create a form layout in mobile-app that can somehow send an API request to netlify-form (if possible), the form will be used to join coala org asking about user details and taking input of an issue reference on which the user want to work (optional)
   - List out all newcomer issues
   - display the joining's of new contributors in past month and past year, to motivate the new joining user

2. Integrate-coala
   - Will work online as well as offline
   - **OFFLINE**: Any project in mobile storage will not require internet to run coala on it.
   - **ONLINE**: Any project uploaded on GitHub or on any other service, requires internet to fetch files.

3. About and Settings section

4. Feedback form

5. PR pending for review
   - Either redirect user to web-page on choosing a PR or display all comments under a PR on the app itself
   - User/Contributor can also comment on a PR

6. User profile
   - Created Issues/PR
   - rest all the mandatory sections that are always present in a profile section

7. Create an Issue form

For now, this is all what I have in mind. I was too thinking about applying Machine Learning somehow but that's just a thought. Will think on it definitely on how can we achieve this. 
Your thoughts are valuable to me, please add a comment if you want to add some new ideas to this project proposal.

**Comment by KVGarg** [comment]
@jayvdb @Makman2 @li-boxuan can you guys please review on this project project ?

**Comment by AkshJain99** [comment]
@KVGarg r u talking about android application? But ithink coala has not still started working android technology.

**Comment by KVGarg** [comment]
Hi @AkshJain99 I have read somewhere a leadership quote - "Don't think out of box as it is overused rather than create a box", inspired by this quote I have proposed this idea. Also, I think GSoC is one of the platforms where all ideas are welcomed and the proposed idea should be good enough to help an organization. That's why, I have come with this idea.

**Comment by AkshJain99** [comment]
Ya I know and I appreciate this idea , I was asking becoz coala hasn't not
started using android yet , btw great idea :+1:

**Comment by frextrite** [comment]
Regarding point 2. Are you proposing that coala should run on projects on the device? I'm asking this because python cannot run natively on Android. Though we have some 3rd party packages for this task, currently none of them work perfectly out of the box.

**Comment by KVGarg** [comment]
Hi @frextrite actually I was thinking to use `coala-online` here to run coala on the local storage or on the online files.
Currently, the coala-online isn't working, but I'm looking further to solve it and looking if we can use some another way.

**Comment by shashank-b** [comment]
Hey @KVGarg 
While I appreciate the out-of-the-box (and quite exciting) idea, I have a few basic questions. Apologies, if this is not the correct way to think about a proposed project. -

- Do you think there is a demand for this? For eg. are there enough people in coala community who felt the need for coala as a smartphone app? (Or if enough demand can be created for this? Though, creating demand is much much harder.)
- Do you think that the results would outperform the efforts put in? This would require a lot of hours put in by the mentor and the person implementing this, and everyone who later ends up maintaining this. Do you think it would be worth it? (Somewhat related to the previous question.)
- Do you think the existing smartphone-coding-ecosystem is good enough to support this? I am asking this because I have tried coding on the go for one whole summer when I had to travel excessively, and didn't find the smartphone experience good enough for that. Tablets are bearable. (Notepads and Laptops are great btw.)
- Aren't the 7 points that you mentioned hitting very versatile areas? What I mean here is that usually Apps that perform a specific function and perform that very well do much better than those trying to do a little bit of everything. Most of these actions are quite comfortably done on the web platform of coala.io or github.com already.
- I am really curious about how you plan to add ML to all this. Any initial thoughts?

While your project is really interesting, it would essentially take up a slot that is offered to coala and a lot of effort, so discussing these answers might be worthwhile.

**Comment by KVGarg** [comment]
> Do you think there is a demand for this? For eg. are there enough people in coala community who felt the need for coala as a smartphone app?

I haven't done any analysis whether the members of coala community really need this app. But I think if we're able to create this app, then members can keep track of there progress because currently, there is no way a member can track the progress. Also, sometimes during contribution we may open too many tabs in our browser and comment on the issues to get assigned or put up a query, and it happens most of times that user closes that tab and if that user has another query and want to look over the issue, that user has to again search for that issue in the issue list. So, I think making this as a track the user can easily track the issues


> if enough demand can be created for this? Though, creating demand is much much harder.

Creating demand is a harder thing, but if someone gets to know that what a particular app do than that user will surely try to use it. Say, we currently use web gitter to chat. Since we are using gitter and all time we can keep open gitter website on our smartphone on laptop. Then to make this easy, we use gitter mobile application. And, the people around me will be curious to know what is this application for and why I'm using this, and this happens many of time while playing games also, taking example of PUBG. If atleast 50 contributors have started using, then I'm sure more 'n' more people will find this helpful.

> Do you think that the results would outperform the efforts put in? This would require a lot of hours put in by the mentor and the person implementing this, and everyone who later ends up maintaining this. Do you think it would be worth it? (Somewhat related to the previous question

If both the mentor and the person implementing this have right knowledge in the right direction, I think it will be worth. And, currently the youth is moving equally towards web development as well as app developemnt which will surely result in inviting new contributors to coala org because we have all our projects setup on web, there is no project for app developers. So, I think this can be a good project for app developers as newcomer.

> Do you think the existing smartphone-coding-ecosystem is good enough to support this? I am asking this because I have tried coding on the go for one whole summer when I had to travel excessively, and didn't find the smartphone experience good enough for that. Tablets are bearable. (Notepads and Laptops are great btw.)

Yeah, Notepads and laptops are great and the companies have also been making portable laptops from past many years. But, we can't carry them everywhere I hope you are understanding me :smile: In that case, we do have either tablet or smartphone( majorly). If this application can ease my life without putting extra weight on my shoulders, I think it will be good. 
A developer merely spends 10-15 mins(max) out of 1hr on smartphone during normal days. While travelling, the contributor might be on holiday and in that I also don't expect taht contributor to spend major time on app which will definitely make family angry :smile: In that case, the contributor can definitely use it to just surf the issues or can look over his progress in free time without spoiling its holiday. Can you tell me in which way you travelled exessively - I mean what was the avg. time you spent between switching vehicles or trnasport? If you have less time gap say 25-30 mis, then it will surely be difficult to carry laptop, but more than 1 hr time gap - the contributor will definitely find difficult using smartphone in that case laptop will work better.

> Aren't the 7 points that you mentioned hitting very versatile areas? What I mean here is that usually Apps that perform a specific function and perform that very well do much better than those trying to do a little bit of everything. Most of these actions are quite comfortably done on the web platform of coala.io or github.com already.

Yes, you are correct that most of them will be comfortable on the web platform but, as I have highlighted earlier that not everywhere you can work from web. Also, if UI/UX is good, then contributors will indulge more in the app rather than working from web like browsing for issues, feedback, tracking of progress etc. 

> I am really curious about how you plan to add ML to all this. Any initial thoughts?

I was thinking to predict the time the contributor will take to solve the issue based upon the difficulty level of issue and the issues the contributor has solved in past, this may include a large dataset - may include data of many other users also (thinking on it), which can be used to do analysis? (Not sure about this at all). was thinking more but can't get much time to think upon it :smile:

Wow, a good amount of quality questions @shashank-b . It actually made me feel happy 👍 Thnx

**Comment by KVGarg** [comment]
> I think during the GCI period, something like a leaderboard exists.

I want that users can track there progress anytime whereas GCI period is only for a limited time where leaderboard is displayed till the GCI period.

> I think github already provides one's activity history and notifications to achieve this. You can simple get notifications for that issue/PR etc. to stay updated, and if you have commented on it previously, it would show up in the history.

True, I agree with this.

> the primary goal should be the usefullness of the app

Won't this project be useful to community?

> I am sorry, I wasn't able to make myself clear. By the web platform I meant accessing coala.io or github.com on the smartphone browsers. I feel that they are good enough, aren't they? Also the leaderboard and contribution history addresses the 'progress' issue (I have mentioned these above, and also coala keeps a track of top contributors in many other ways as well).

They are good, I'm not saying that they aren't good. All of them are responsive. But I thought why not to have mobile application also.

**Comment by KVGarg** [comment]
Dropping out the idea of application. Somewhat satisfied by your questions and also, by one of the developers talk.
