### ISSUE TITLE
Support TOML as another settings file format 

### ISSUE THREAD

**Issue by PrajwalM2212** [coala/projects#705]
According to https://github.com/toml-lang/toml
TOML aims to be a minimal configuration file format that's easy to read due to obvious semantics. TOML is designed to map unambiguously to a hash table. TOML should be easy to parse into data structures in a wide variety of languages.

TOML has widespread acceptance, documentation and robust parsers. 
Also according to https://www.python.org/dev/peps/pep-0518/, TOML is
 1. Human-usable (unlike JSON ), 
 2. Flexible (unlike configparser), 
 3. Stems from a standard (unlike configparser)
 4. Not overly complex (unlike YAML).

Also TOML has been recommended as the configuration file for software packages to specify their build dependencies. 
` pyproject.toml` is being used for this purpose. https://github.com/pypa/pip/blob/master/pyproject.toml

coala could provide TOML as a additional setting format. 
1. By following a well known standard like TOML, we would reduce the learning curve involved. 
2. When the current system gets complex, TOML will be a better choice than a custom INI.
3. It provides flexibility, consistency, backwards compatibility and stems from a standard all of which are drawbacks of configparser.

This proposal issue is about supporting a new config file like `coafile.toml` along with `.coafile`. 

https://github.com/coala/coala/issues/4609

**Comment by li-boxuan** [comment]
Similar to https://github.com/coala/projects/issues/702

**Comment by PrajwalM2212** [comment]
Thanks @li-boxuan . The only overlap I saw was  `Standardising .coafile syntax for starters using YAML`  but also this chooses TOML as its a better choice comapred to YAML.

**Comment by PrajwalM2212** [comment]
@userzimmermann @fneu Would you like to be a mentor for this project ?

**Comment by jayvdb** [comment]
See https://gitter.im/coala/coala?at=5bfe8cb5f849b222e0b8bad7 , by @underyx , which provides a very good reason for the settings to be in a standardised file format.

**Comment by PrajwalM2212** [comment]
Thank you @jayvdb . That is one of the most compelling reasons in defence of the project idea.

**Comment by RaiVaibhav** [comment]
Great idea and thank you @PrajwalM2212 for pinging me for this, I can't mentor on the project as I have not applied for the mentor but If you need any help you know how to ping me 😛 and I will try my best to assist you asap.

**Comment by RaiVaibhav** [comment]
@Makman2 @jayvdb Is this possible that I can help @PrajwalM2212 officially ?
