### ISSUE TITLE
Different order of projects in detailed view

### ISSUE THREAD

**Issue by areebbeigh** [coala/projects#711]
Steps to reproduce:

- Go to https://projects.coala.io/#/projects
- Open the first project
- Click next (arrow)

The next project is not the same as the 2nd project in the grid view.

**Comment by KVGarg** [comment]
@areebbeigh are you currently looking over it, to solve this ?

**Comment by areebbeigh** [comment]
Nope. It's unassigned.

**Comment by KVGarg** [comment]
Currently, an `orderBy` filter is being applied to the projects which sorts them according to status of projects but it is not storing that sorted projects list anywhere due to which on the initial array(unsorted array) of projects is being used to navigate between projects using those arrows

**Comment by KVGarg** [comment]
@li-boxuan can I take this ?
