### ISSUE TITLE
Travis CI also failing due to Spacing Inconsistencies

### ISSUE THREAD

**Issue by KVGarg** [coala/projects#713]
The issue is in reference to PR#700
Travis build failure error log - https://github.com/coala/projects/pull/700#issuecomment-460352115

A difficult/newcomer issue

**Comment by NoumbissiValere** [comment]
@KVGarg Please i will love to solve this issue

**Comment by KVGarg** [comment]
@NoumbissiValere Please ask on gitter to get yourself on it. I don't have permissions to assign anyone.

**Comment by jayvdb** [comment]
This was already done by @kriti21 	in https://github.com/coala/projects/pull/600 , which I have tidied up and merged.
