### ISSUE TITLE
"use_spaces" setting missing in html section

### ISSUE THREAD

**Issue by KVGarg** [coala/projects#723]
Running `coala` over this repository raises a prompt error asking for "use_spaces" setting which shouldn't happen!

**Comment by VishalBhosale5** [comment]
May i work on this issue

**Comment by KVGarg** [comment]
You can ask on gitter to get assigned to it, if it’s a valid issue.

**Comment by abhishalya** [comment]
Already known, to be fixed via https://github.com/coala/projects/pull/600.

**Comment by jayvdb** [comment]
This was a regression in bears, and should be fixed there.  c.f. https://github.com/coala/coala-bears/issues/2949
