### ISSUE TITLE
Add an FAQ related to Google Season of Docs

### ISSUE THREAD

**Issue by KVGarg** [coala/projects#742]

**Comment by arzoo14** [comment]
@KVGarg 
Can you tell me which FAQ to add?

**Comment by KVGarg** [comment]
> Can you tell me which FAQ to add?

It'll good to add an FAQ related to GSoD that *what it is all about?* and *whether coala will be partcipating in it or not?* etc.

**Comment by abhishalya** [comment]
Closing this as coala hasn't participated in GSoD yet. This can be opened up once we have a plan around that.
