### ISSUE TITLE
Spelling correction.

### ISSUE THREAD

**Issue by Chaitanyassr** [coala/projects#773]
- "Similiarly" should be "Similarly" in Multi Language Support.
- "file" should be "files" in Multi Language Support.
- "the" should be added between "be same" in Multi Language Support.

**Comment by faraz16iqbal** [comment]
Hi, Can I work on this issue?

**Comment by pra17dod** [comment]
Hi @abhishalya, as the issue was idle since a long time, I fixed it in the PR #790. Please review it.
