### ISSUE TITLE
Improve filter projects 

### ISSUE THREAD

**Issue by itssingh** [coala/projects#785]
The close sign for filter projects is not aligned properly.
![image](https://user-images.githubusercontent.com/43489890/110758189-3a3eaa00-8272-11eb-94ec-55a76f7989d9.png)
difficulty level: good first issue

**Comment by sidharth1017** [comment]
Hello i want to fix this close sign please assign me this issue.

**Comment by abhishalya** [comment]
Assignment not required, go ahead

**Comment by sidharth1017** [comment]
Could you please help me in setting up codebase in my local host??

**Comment by sidharth1017** [comment]
@abhishalya Could you please help me in setting up codebase in my local host??

**Comment by abhishalya** [comment]
Have you followed the readme?

If you're facing any issues, ask them on gitter.

**Comment by pra17dod** [comment]
Hi @abhishalya, I have fixed this issue in PR #789. Please review it.

**Comment by pra17dod** [comment]
Hi @abhishalya, I made the changes and made proper commits. Please review it.
