### ISSUE TITLE
Add a tag and difficulty row in the project section

### ISSUE THREAD

**Issue by itssingh** [coala/projects#786]
Adding tags and difficulty row down the mentors name row will help in providing the project overview to a great extent. 

![image](https://user-images.githubusercontent.com/43489890/110761164-6dcf0380-8275-11eb-8cc5-5a5908250cb9.png)

**Comment by pra17dod** [comment]
Hi @abhishalya, I fixed this issue in PR #789. Please review it.

**Comment by pra17dod** [comment]
Hi @abhishalya, I added this changes in PR #792. Please review it.
