### ISSUE TITLE
Flesh out descriptions

### ISSUE THREAD

**Issue by sils** [coala/projects#81]
Generally the descriptions of the projects in here aren't well enough and could be more verbose. The ideas need to be fleshed out.

**Comment by sils** [comment]
CC @sims1253 the ideas page is vital, this is highly relevant and also this is based on feedback from the PSF to our current projects

**Comment by sims1253** [comment]
@myint could you come up with a nice description for the gsoc project ([see current version here](http://projects.coala.io/#/projects?project=improve_sphinx_support_in_rstcheck)
We (or rather google) would like to have a motivation for for why this project is needed and what problem it solves and a goal it wants to reach for each project. Any help would be appreciated.
File is here: https://github.com/coala/projects/blob/master/data/projects/rstcheck_with_better_sphinx_support.md

**Comment by myint** [comment]
I'll try expanding it this weekend.

**Comment by jayvdb** [comment]
Student slots filled.
Any additional improvements to the descriptions can be addressed with separate issues.
