### ISSUE TITLE
I need to be able to get a link to a project

### ISSUE THREAD

**Issue by sils** [coala/projects#96]

**Comment by hemangsk** [comment]
What'll be the better way to have project links,

- Full project name with spaces replaced by underscore, will open the project details view
Eg: http://projects.coala.io/improve_diff_handling 

or  Searching requested text in search box 
http://projects.coala.io/search=improve_diff_handling

**Comment by sils** [comment]
both, the full name is more important and should give the details view, the search should open the page with the search query

**Comment by sils** [comment]
@hemangsk unassigning you for now since this approach isn't the right one and you're on other things right now.

We probably want:

- `/mentors` and `/projects` and `/faqs` for the pages
- `?project=...` or `?q=...` for search queries and the project view
